### ISSUE TITLE
New Firefox Icon

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Faenza-NewVanilla/faenza-newvanilla-icon-theme#13]
```
Firefox have a new icon. Faenza should be update.
```

Original issue reported on code.google.com by `mtlcny...@gmail.com` on 30 Dec 2013 at 3:19

**Comment by Kazhnuz** [comment]
Closing, as the new icon (pulled from Mint-X IIRC) works well with the design of Faenza. Will be reopened if someone want :)
